---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cham.
--- DateTime: 2025/9/20 18:02
---

local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

local stockKey = "seckill:stock:" .. voucherId
local orderKey = "seckill:order:" .. voucherId

-- 判断库存是否充足
if (tonumber(redis.call("get", stockKey)) <= 0) then
    -- 库存不足, 返回1
    return 1
end
-- 判断用户是否下单
if (redis.call("sismember", orderKey, userId) == 1) then
    -- 用户已经下单, 返回2
    return 2
end

-- 库存充足, 下单
redis.call('incrby', stockKey,-1)
redis.call('sadd', orderKey, userId)
-- 发送消息
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0